version: "3.7"
services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: belf-mysql
    container_name: mysql-dev
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      # 한글과 이모지 입력을 위하여 기본 문자셋 인코딩 변경
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:6.2.4-alpine
    container_name: redis-dev
    ports:
      - 6379:6379
  oauth-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: belf-oauth-server
    depends_on:
      - mysql
    container_name: oauth-server-dev
    ports:
      - 3001:8080
    environment:
      - SWAGGER_PORT=3001
